jhack/main.py
setup.py

the python package missed an include directive and the unbork_juju script was not being bundled as a consequence. This should fix that. Also better cli help

fixed unbork script packaging

---

README.md
jhack/helpers.py
jhack/main.py
jhack/tests/utils/memo_tools_test_files/trfk-re-relate.json
jhack/utils/event_recorder/client.py
jhack/utils/event_recorder/runtime.py
jhack/utils/integrate.py
jhack/utils/show_relation.py
jhack/utils/tail_charms.py

commands to view and manage all possible integrations between your deployed applications -- not just those that happen to be active.

Relation matrix

---

jhack/main.py
jhack/tests/utils/memo_tools_test_files/trfk-re-relate.json
jhack/tests/utils/test_replay_local_runtime.py
jhack/utils/event_recorder/runtime.py
jhack/utils/show_relation.py
jhack/utils/simulate_event.py
jhack/utils/sync.py
jhack/utils/unleash.py
tox.ini

- adds functionality to `jhack sync` to simultaneously push to all units of an application
- fixes bug in show-relation (peer)

Sync to app

---

README.md
jhack/conf/conf.py
jhack/conf/jhack_config_defaults.toml
jhack/config.py
jhack/main.py
jhack/tests/config/test_config.py
jhack/utils/nuke.py
jhack/utils/simulate_event.py
jhack/utils/tail_charms.py

This PR adds a confirmation dialog for `jhack nuke`.
Also adds a thin config layer to allow suppressing/enabling that dialog.
fixes #34

Nuke confirm

---

jhack/utils/simulate_event.py
jhack/utils/tail_charms.py

fixed fire in lxd models

---

README.md
jhack/utils/show_relation.py

a bit hacky still, might need some refactor to make the code a cleaner.
Also: optimize the hell out of those juju status calls.
Fixes #60

subordinate charm support for show-relation

---

jhack/utils/integrate.py

added check for terminated applications

---

jhack/charm/provision.py
jhack/conf/conf.py
jhack/config.py
jhack/main.py
jhack/utils/show_relation.py

and simplified here and there the whole config codepath. It was... too creative.
Fixes #67

fixed bug in config if os.getpwuid uid fails

---

jhack/conf/conf.py
jhack/config.py
jhack/main.py
jhack/tests/utils/test_tail.py
jhack/utils/integrate.py
jhack/utils/show_relation.py
jhack/utils/tail_charms.py
pyproject.toml
snap/snapcraft.yaml

Tail custom evts

---

jhack/utils/print_env.py

catch FileNotFoundError in the case multipass is not installed

---

jhack/helpers.py
jhack/tests/utils/list_endpoints_mocks/full_status.json
jhack/tests/utils/list_endpoints_mocks/keystone_metadata.yaml
jhack/tests/utils/list_endpoints_mocks/keystone_mysql_router_0_show.yaml
jhack/tests/utils/test_list_endpoints.py
jhack/utils/list_endpoints.py
jhack/utils/print_env.py
pyproject.toml

only attempt to gather bound remotes if jujuv<=3.1

---

jhack/utils/list_endpoints.py
jhack/utils/tail_charms.py

fixed option definition in tail

---

jhack/config.py
jhack/utils/list_endpoints.py
jhack/utils/tail_charms.py
snap/snapcraft.yaml

bump the wrapped juju snap channel to 3.3/beta

Bump juju v

---

jhack/config.py
jhack/utils/show_relation.py
jhack/utils/tail_charms.py

toggle caching in show-relation based on -w

---

README.md

As far as I can tell, the syntax here is out of date. Please correct me if I'm wrong.

fix(README): fix syntax for jhack sync

---

jhack/charm/vinfo.py
jhack/helpers.py
pyproject.toml

Fixes #106 
allows `jhack charm vinfo /path/to/charm/repo`

Vinfo for local charm

---

jhack/charm/vinfo.py
jhack/main.py
jhack/scenario/dict_to_state.py
jhack/scenario/integrations/darkroom.py
jhack/scenario/snapshot.py
jhack/scenario/state_apply.py
jhack/scenario/utils.py
jhack/tests/test_scenario/test_darkroom/test_harness_integration/test_integrations_harness.py
jhack/tests/test_scenario/test_darkroom/test_scenario_integration/test_install_scenario.py
jhack/tests/test_scenario/test_darkroom/test_scenario_integration/test_integrations_scenario.py
jhack/tests/test_scenario/test_snapshot/test_dict_to_state.py
jhack/tests/test_scenario/test_snapshot/test_fs_push_pull.py
jhack/tests/test_scenario/test_snapshot/test_state_apply.py

Fix imports

---

jhack/scenario/dict_to_state.py
jhack/scenario/integrations/darkroom.py
jhack/scenario/snapshot.py
jhack/scenario/state_apply.py
jhack/scenario/state_to_dict.py
jhack/tests/test_scenario/test_darkroom/test_harness_integration/test_integrations_harness.py
jhack/tests/test_scenario/test_darkroom/test_scenario_integration/test_install_scenario.py
jhack/tests/test_scenario/test_darkroom/test_scenario_integration/test_integrations_scenario.py
jhack/tests/test_scenario/test_snapshot/test_dict_to_state.py
jhack/utils/sync.py
pyproject.toml

added scenario 6 support for snapshot and state-apply

scenario 6 compat

---

jhack/utils/sync.py
pyproject.toml

initial sync

---

jhack/helpers.py
jhack/main.py
jhack/utils/.charm_rpc_dispatch.py
jhack/utils/charm_rpc.py
jhack/utils/sync.py
pyproject.toml

- introduces crpc command
- fixes #131

crpc command; sync bugfix

---

README.md
jhack/charm/lobotomy.py
jhack/helpers.py
jhack/utils/charm_rpc.py
jhack/utils/simulate_event.py
jhack/utils/tail_charms.py
pyproject.toml

Fixes #142 
Adds:
- `jhack fire foo/leader event` --> fires on leader unit
- `jhack fire foo event`  -->  fires on all units

fire on all and leader

---

jhack/helpers.py
pyproject.toml

allow for principal being set up

---

jhack/utils/sync.py
pyproject.toml

Fix subordinate application target expansion in `jhack sync`
Fixes #176

fix sync for subordinate apps

---

jhack/scenario/snapshot.py
jhack/utils/integrate.py
jhack/utils/sync.py
jhack/utils/tail_charms.py
tox.ini

Adds a `--venv` flag to `jhack sync` allowing you to sync all the python packages in a venv directory to a charm's venv.

sync venv feature

---

jhack/helpers.py
jhack/utils/tail_charms.py
pyproject.toml

Fix file targets

---

jhack/helpers.py
jhack/main.py
jhack/tests/utils/test_tail_logs.py
jhack/utils/charm_rpc_dispatch.py
jhack/utils/event_recorder/memo_tools.py
jhack/utils/list_endpoints.py
jhack/utils/show_stored.py
jhack/utils/tail_charms.py
jhack/utils/tail_logs.py

Fixes #193 
made the tool more configurable, allowing to show/hide all columns
minimal:
full:

added description to show-endpoints

---

jhack/tests/utils/test_tail.py
jhack/utils/list_endpoints.py
jhack/utils/tail_charms.py
jhack/utils/unleash.py

major cleanup of some very old code in tail
should also address off-by-one errors such as the one causing #196 
Fixes #196

Tail refactor
